/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-02-09 03:15:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class _04_005fPizzaOrderForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/datePrint.jsp", Long.valueOf(1675912118090L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>피자 주문 페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("	span{color:pink;}\r\n");
      out.write("	table{border-collapse:collapse;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	h1{color:red;}\r\n");
      out.write("	span{color:pink;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");

	
		Date date = new Date();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 E요일");
		String today = sdf.format(date);
		
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h4>오늘은 <span>");
      out.print( today );
      out.write("</span> 입니다.</h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<h4>피자아카데미</h4>\r\n");
      out.write("	\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>종류</th>\r\n");
      out.write("			<th>이름</th>\r\n");
      out.write("			<th>가격</th>\r\n");
      out.write("			<th rowspan=\"12\"></th>\r\n");
      out.write("			<th>종류</th>\r\n");
      out.write("			<th>이름</th>\r\n");
      out.write("			<th>가격</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td rowspan=\"5\">피자</td>\r\n");
      out.write("			<td>치즈피자</td>\r\n");
      out.write("			<td>5000</td>\r\n");
      out.write("			<td rowspan=\"11\">사이드</td>\r\n");
      out.write("			<td>오븐구이통닭</td>\r\n");
      out.write("			<td>9000</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>콤비네이션 피자</td>\r\n");
      out.write("			<td>6000</td>\r\n");
      out.write("			<td>치킨스틱&윙</td>\r\n");
      out.write("			<td>4900</td>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>포테이토피자</td>\r\n");
      out.write("			<td>7000</td>\r\n");
      out.write("			<td>치즈오븐스파게티</td>\r\n");
      out.write("			<td>4000</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>고구마피자</td>\r\n");
      out.write("			<td>7000</td>\r\n");
      out.write("			<td>새우링&웨지감자</td>\r\n");
      out.write("			<td>3500</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>불고기피자</td>\r\n");
      out.write("			<td>8000</td>\r\n");
      out.write("			<td>갈릭포테이토</td>\r\n");
      out.write("			<td>3000</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td rowspan=\"6\">토핑</td>\r\n");
      out.write("			<td>고구마무스</td>\r\n");
      out.write("			<td>1000</td>\r\n");
      out.write("			<td>콜라</td>\r\n");
      out.write("			<td>1500</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>콘크림무스</td>\r\n");
      out.write("			<td>1500</td>\r\n");
      out.write("			<td>사이다</td>\r\n");
      out.write("			<td>1500</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>파인애플토핑</td>\r\n");
      out.write("			<td>2000</td>\r\n");
      out.write("			<td>갈릭소스</td>\r\n");
      out.write("			<td>500</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>치즈토핑</td>\r\n");
      out.write("			<td>2000</td>\r\n");
      out.write("			<td>피클</td>\r\n");
      out.write("			<td>300</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>치즈크러스트</td>\r\n");
      out.write("			<td>2000</td>\r\n");
      out.write("			<td>핫소스</td>\r\n");
      out.write("			<td>100</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>치즈바이트</td>\r\n");
      out.write("			<td>3000</td>\r\n");
      out.write("			<td>파마산치즈가루</td>\r\n");
      out.write("			<td>100</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"/jsp/test.do\" method=\"post\">\r\n");
      out.write("		\r\n");
      out.write("		피자 : \r\n");
      out.write("		<select name=\"pizzaname\">\r\n");
      out.write("			<option>치즈피자</option>\r\n");
      out.write("			<option>콤비네이션피자</option>\r\n");
      out.write("			<option>포테이토피자</option>\r\n");
      out.write("			<option>고구마피자</option>\r\n");
      out.write("			<option>불고기피자</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		토핑 : \r\n");
      out.write("		<input type=\"checkbox\" name=\"top\" value=\"고구마무스\">고구마무스\r\n");
      out.write("		<input type=\"checkbox\" name=\"top\" value=\"콘크림무스\">콘크림무스\r\n");
      out.write("		<input type=\"checkbox\" name=\"top\" value=\"파인애플토핑\">파인애플토핑\r\n");
      out.write("		<input type=\"checkbox\" name=\"top\" value=\"치즈토핑\">치즈토핑\r\n");
      out.write("		<input type=\"checkbox\" name=\"top\" value=\"치즈크러스트\">치즈크러스트\r\n");
      out.write("		<input type=\"checkbox\" name=\"top\" value=\"치즈바이트\">치즈바이트\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		사이드 :\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"오븐구이통닭\">오븐구이통닭\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"치킨스틱&윙\">치킨스틱&윙\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"치즈오븐스파게티\">치즈오븐스파게티\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"새우링&웨지감자\">새우링&웨지감자\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"갈릭포테이토\">갈릭포테이토\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"콜라\">콜라\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"사이다\">사이다\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"갈릭소스\">갈릭소스\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"피클\">피클\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"핫소스\">핫소스\r\n");
      out.write("		<input type=\"checkbox\" name=\"side\" value=\"파마산 치즈가루\">파마산 치즈가루\r\n");
      out.write("		<br><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<input type=\"submit\" value=\"확인\">\r\n");
      out.write("	\r\n");
      out.write("	</form>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
